language: rust
sudo: false
rust:
  # 1.13.0 is the earliest version that Serde 1.0 tests, so we follow suit
  - 1.13.0
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
      env: CLIPPY=n
  include:
    - rust: nightly
      env: CLIPPY=y

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
    - CLIPPY: n
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source $HOME/.nvm/nvm.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then nvm install 10; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then nvm use 10; fi
  - if [ "$TRAVIS_RUST_VERSION" != "1.13.0" ]; then curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh; fi
script: ./ci/travis.sh
notifications:
  email: false
  irc:
    channels:
      - "irc.mozilla.org#chronotope"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
